"""remove review and modification fields

Revision ID: 119cbe418079
Revises: 68fb77a0c339
Create Date: 2026-02-10 06:25:52.839673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '119cbe418079'
down_revision: Union[str, Sequence[str], None] = '68fb77a0c339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fax_jobs', 'review_needed')
    op.drop_column('fax_jobs', 'has_human_modifications')
    op.drop_column('fax_jobs', 'modified_fields')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fax_jobs', sa.Column('modified_fields', sa.TEXT(), nullable=True))
    op.add_column('fax_jobs', sa.Column('has_human_modifications', sa.BOOLEAN(), nullable=True))
    op.add_column('fax_jobs', sa.Column('review_needed', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
