"""add_job_level_modification_tracking

Revision ID: 68fb77a0c339
Revises: bbccbf653600
Create Date: 2026-02-01 11:45:27.026584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68fb77a0c339'
down_revision: Union[str, Sequence[str], None] = 'bbccbf653600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fax_jobs', sa.Column('has_human_modifications', sa.Boolean(), nullable=True))
    op.add_column('fax_jobs', sa.Column('modified_fields', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fax_jobs', 'modified_fields')
    op.drop_column('fax_jobs', 'has_human_modifications')
    # ### end Alembic commands ###
