"""add_human_modification_tracking

Revision ID: bbccbf653600
Revises: 2992d4467f57
Create Date: 2026-02-01 11:41:11.402085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbccbf653600'
down_revision: Union[str, Sequence[str], None] = '2992d4467f57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fax_extracted_fields', sa.Column('human_modified', sa.Boolean(), nullable=True))
    op.add_column('fax_extracted_fields', sa.Column('human_modified_at', sa.DateTime(), nullable=True))
    op.add_column('fax_extracted_fields', sa.Column('human_modified_by', sa.String(), nullable=True))
    op.add_column('fax_extracted_fields', sa.Column('original_ai_value', sa.Text(), nullable=True))
    op.create_index(op.f('ix_fax_extracted_fields_id'), 'fax_extracted_fields', ['id'], unique=False)
    op.drop_column('fax_extracted_fields', 'page_number')
    op.create_index(op.f('ix_fax_jobs_id'), 'fax_jobs', ['id'], unique=False)
    op.drop_column('fax_jobs', 'processed_pages')
    op.drop_column('fax_jobs', 'total_pages')
    op.create_index(op.f('ix_human_labels_id'), 'human_labels', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_human_labels_id'), table_name='human_labels')
    op.add_column('fax_jobs', sa.Column('total_pages', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fax_jobs', sa.Column('processed_pages', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_fax_jobs_id'), table_name='fax_jobs')
    op.add_column('fax_extracted_fields', sa.Column('page_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_fax_extracted_fields_id'), table_name='fax_extracted_fields')
    op.drop_column('fax_extracted_fields', 'original_ai_value')
    op.drop_column('fax_extracted_fields', 'human_modified_by')
    op.drop_column('fax_extracted_fields', 'human_modified_at')
    op.drop_column('fax_extracted_fields', 'human_modified')
    # ### end Alembic commands ###
