-- PAOCR application schema.
-- This file is intentionally idempotent so it can initialize a fresh database
-- or be applied again by the postgres-schema compose service.

BEGIN;

CREATE TABLE IF NOT EXISTS fax_jobs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id varchar NOT NULL,
    sha256 varchar(64) NOT NULL,
    status varchar,
    created_at timestamp without time zone,
    finalized_at timestamp without time zone,
    total_pages integer,
    review_needed boolean,
    has_human_modifications boolean,
    modified_fields text
);

ALTER TABLE fax_jobs
    ADD COLUMN IF NOT EXISTS tenant_id varchar,
    ADD COLUMN IF NOT EXISTS sha256 varchar(64),
    ADD COLUMN IF NOT EXISTS status varchar,
    ADD COLUMN IF NOT EXISTS created_at timestamp without time zone,
    ADD COLUMN IF NOT EXISTS finalized_at timestamp without time zone,
    ADD COLUMN IF NOT EXISTS total_pages integer,
    ADD COLUMN IF NOT EXISTS review_needed boolean,
    ADD COLUMN IF NOT EXISTS has_human_modifications boolean,
    ADD COLUMN IF NOT EXISTS modified_fields text;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uq_fax_jobs_sha256'
          AND conrelid = 'fax_jobs'::regclass
    ) THEN
        ALTER TABLE fax_jobs ADD CONSTRAINT uq_fax_jobs_sha256 UNIQUE (sha256);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS fax_extracted_fields (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fax_job_id integer NOT NULL,
    field_key varchar NOT NULL,
    value text,
    method varchar,
    confidence double precision,
    evidence_bbox json,
    evidence_text text,
    candidates json,
    validated boolean,
    human_modified boolean,
    human_modified_at timestamp without time zone,
    human_modified_by varchar,
    original_ai_value text
);

ALTER TABLE fax_extracted_fields
    ADD COLUMN IF NOT EXISTS fax_job_id integer,
    ADD COLUMN IF NOT EXISTS field_key varchar,
    ADD COLUMN IF NOT EXISTS value text,
    ADD COLUMN IF NOT EXISTS method varchar,
    ADD COLUMN IF NOT EXISTS confidence double precision,
    ADD COLUMN IF NOT EXISTS evidence_bbox json,
    ADD COLUMN IF NOT EXISTS evidence_text text,
    ADD COLUMN IF NOT EXISTS candidates json,
    ADD COLUMN IF NOT EXISTS validated boolean,
    ADD COLUMN IF NOT EXISTS human_modified boolean,
    ADD COLUMN IF NOT EXISTS human_modified_at timestamp without time zone,
    ADD COLUMN IF NOT EXISTS human_modified_by varchar,
    ADD COLUMN IF NOT EXISTS original_ai_value text;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_fax_extracted_fields_fax_job_id'
          AND conrelid = 'fax_extracted_fields'::regclass
    ) THEN
        ALTER TABLE fax_extracted_fields
            ADD CONSTRAINT fk_fax_extracted_fields_fax_job_id
            FOREIGN KEY (fax_job_id) REFERENCES fax_jobs(id);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS human_labels (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fax_job_id integer NOT NULL,
    field_key varchar NOT NULL,
    ai_value text,
    ai_confidence double precision,
    human_value text,
    human_action varchar,
    review_time_seconds double precision,
    reviewer_id varchar,
    created_at timestamp without time zone,
    page_number integer,
    bbox json
);

ALTER TABLE human_labels
    ADD COLUMN IF NOT EXISTS fax_job_id integer,
    ADD COLUMN IF NOT EXISTS field_key varchar,
    ADD COLUMN IF NOT EXISTS ai_value text,
    ADD COLUMN IF NOT EXISTS ai_confidence double precision,
    ADD COLUMN IF NOT EXISTS human_value text,
    ADD COLUMN IF NOT EXISTS human_action varchar,
    ADD COLUMN IF NOT EXISTS review_time_seconds double precision,
    ADD COLUMN IF NOT EXISTS reviewer_id varchar,
    ADD COLUMN IF NOT EXISTS created_at timestamp without time zone,
    ADD COLUMN IF NOT EXISTS page_number integer,
    ADD COLUMN IF NOT EXISTS bbox json;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_human_labels_fax_job_id'
          AND conrelid = 'human_labels'::regclass
    ) THEN
        ALTER TABLE human_labels
            ADD CONSTRAINT fk_human_labels_fax_job_id
            FOREIGN KEY (fax_job_id) REFERENCES fax_jobs(id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS ix_fax_jobs_id ON fax_jobs (id);
CREATE INDEX IF NOT EXISTS ix_fax_jobs_tenant_id ON fax_jobs (tenant_id);
CREATE INDEX IF NOT EXISTS ix_fax_jobs_status ON fax_jobs (status);
CREATE INDEX IF NOT EXISTS ix_fax_extracted_fields_id ON fax_extracted_fields (id);
CREATE INDEX IF NOT EXISTS ix_fax_extracted_fields_fax_job_id ON fax_extracted_fields (fax_job_id);
CREATE INDEX IF NOT EXISTS ix_fax_extracted_fields_field_key ON fax_extracted_fields (field_key);
CREATE INDEX IF NOT EXISTS ix_human_labels_id ON human_labels (id);
CREATE INDEX IF NOT EXISTS ix_human_labels_fax_job_id ON human_labels (fax_job_id);
CREATE INDEX IF NOT EXISTS ix_human_labels_field_key ON human_labels (field_key);

CREATE OR REPLACE VIEW extracted_fields_horizontal AS
SELECT
    fj.id AS job_id,
    fj.tenant_id,
    fj.status,
    fj.created_at,
    fj.finalized_at,
    fj.review_needed,
    fj.has_human_modifications,
    fj.modified_fields,
    MAX(CASE WHEN fef.field_key = 'insurance_company_name' THEN fef.value END) AS insurance_company_name,
    MAX(CASE WHEN fef.field_key = 'insurance_member_number' THEN fef.value END) AS insurance_member_number,
    MAX(CASE WHEN fef.field_key = 'insurance_member_name' THEN fef.value END) AS insurance_member_name,
    MAX(CASE WHEN fef.field_key = 'approval_status' THEN fef.value END) AS approval_status,
    MAX(CASE WHEN fef.field_key = 'approval_number' THEN fef.value END) AS approval_number,
    MAX(CASE WHEN fef.field_key = 'approved_service_cpt' THEN fef.value END) AS approved_service_cpt,
    MAX(CASE WHEN fef.field_key = 'approved_units' THEN fef.value END) AS approved_units,
    MAX(CASE WHEN fef.field_key = 'service_start_date' THEN fef.value END) AS service_start_date,
    MAX(CASE WHEN fef.field_key = 'service_end_date' THEN fef.value END) AS service_end_date,
    MAX(CASE WHEN fef.field_key = 'insurance_rep_name' THEN fef.value END) AS insurance_rep_name,
    MAX(CASE WHEN fef.field_key = 'insurance_rep_contact' THEN fef.value END) AS insurance_rep_contact,
    MAX(CASE WHEN fef.field_key = 'fax_received_date' THEN fef.value END) AS fax_received_date
FROM fax_jobs fj
LEFT JOIN fax_extracted_fields fef ON fj.id = fef.fax_job_id
GROUP BY
    fj.id,
    fj.tenant_id,
    fj.status,
    fj.created_at,
    fj.finalized_at,
    fj.review_needed,
    fj.has_human_modifications,
    fj.modified_fields;

COMMIT;
